version: '3'

services:
  dns:
    image: mvance/unbound:1.9.6
    restart: always
    container_name: unbound-dns-resolver
    ports:
      - "953:953/tcp"
      - "5555:53/tcp"
      - "5555:53/udp"
    volumes:
      - "./conf:/opt/unbound/etc/unbound/"
      #- "./conf/resolv.conf:/etc/resolv.conf:ro"