version: '3'

services:
  dnscrypt-server:
    image: jedisct1/dnscrypt-server
    container_name: dnscrypt-server
    restart: unless-stopped
    ports:
      - 4443:443/udp
      - 4443:443/tcp
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    environment:
      - TZ=Europe/Copenhagen
    command: init -N hush.dns -E 172.20.128.3:4443

networks:
  static-network:
    external:
      name: piholed_static-network