version: "3"

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    environment:
      DNSCRYPT_LISTEN_PORT: "5353"
      DNSCRYPT_SERVER_NAMES: "['cloudflare']"
    image: klutchell/dnscrypt-proxy:2.1.2
    network_mode: "host"
    restart: unless-stopped
