version: '3.4'

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    healthcheck:
      test: ["CMD", "drill", "-p", "5053", "cloudflare.com", "@127.0.0.1", "||", "exit", "1"]
      interval: 20s
      timeout: 20s
      retries: 3
      start_period: 5s
    image: klutchell/dnscrypt-proxy:2.1.4
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - "./conf/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml"
